### ISSUE TITLE
Please add Button to download the Resume.pdf from the page.

### ISSUE THREAD

**Issue by VicharSharma** [sproogen/modern-resume-theme#163]
On top right corner or somewhere, request you to please add a clickable download resume button , which will download the resume.pdf.

**Comment by Haki-Malai** [comment]
This is very simple you can do it yourself!
Create the pdf/cv.pdf file. Edit the _config.yml file. Add link for download.
For example:
```yml
# Additional icon links
additional_links:
- title: Pdf Download
  icon: far fa-file-pdf
  url: https://github.com/{your github username}/{your repo name}/raw/main/pdf/cv.pdf
```
Good luck! :)
